python3 configure.py \
 --prob=cr_turb \
 --nghost=2 \
 --eos="adiabatic" \
 --nscalars=1 \
 -b \
 -fft \
 -hdf5 \
 -mpi \
 -omp \
 --mpiccmd=h5pcc \
 --cflag='-DH5_HAVE_PARALLEL -lstdc++' \
 --cxx='g++'
