python3 configure.py \
 --prob=ntf \
 --nghost=4 \
 --coord=cylindrical \
 --flux=roe \
 --eos="adiabatic" \
 -b \
 -cr \
 -hdf5 \
 -mpi \
 -omp \
 --hdf5_path=$HDF5_ROOT \
 --cflag='-DH5_HAVE_PARALLEL ' \
